### ISSUE TITLE
Missing JS source & bower listing

### ISSUE THREAD

**Issue by naganowl** [unamohq/Typist#1]
The README mentions that the library can be found on bower, but I don't see any reference to it (http://bower.io/search/?q=Typist). Also, it mentions downloading the raw JS file however there is no such file in the repo or link to the file (via CDN or another site).

It would make sense to include the JS file somewhere in the repo (or even better, in a separate branch). This [fork](https://github.com/EagerApps/Typist) seems to get this right and has some additional files that this repo could benefit from (such as separated files).

**Comment by oskarkrawczyk** [comment]
@naganowl Weird, it should be available via Bower. Will investigate.

**Comment by rarkins** [comment]
I don't think this repo is useable in current form, especially with no dist files. Will the @EagerApps updates be merged or matched?

**Comment by oskarkrawczyk** [comment]
@rarkins https://github.com/positionly/Typist/blob/master/dist/typist.js – it's been there for a few days already.

**Comment by rarkins** [comment]
Great, thanks. Also, given the similarity to https://github.com/iamchrismiller/typist/, you might want to consider a name change before publishing to bower? The sooner the easier if it's to be done.

**Comment by rarkins** [comment]
Actually I see commits are 2 years old here, so I might be wrong above. Which repo was published and publicized first?

**Comment by oskarkrawczyk** [comment]
Yep, this project/repo was published months before the one you're mentioning.

**Comment by oskarkrawczyk** [comment]
Dist added. Closing. Created #2 for the bower issue.

**Comment by rarkins** [comment]
Seems that other one has the bower name 'typist' though, so you'll need to change names or use a bower name that doesn't match the repository name?
